### ISSUE TITLE
Renaming a device does not work

### ISSUE THREAD

**Issue by StorageB** [swsnr/turnon#22]
If I have an existing device set up and try to edit the device label, it will revert back to the original device name after closing and reopening the app. Steps to reproduce:

1. Add new device, enter all information, and save
2. Edit this device, change the device label, and save
3. Close application and reopen
4. The device label shows the original name that was entered when the device was created instead of the new name.

**Comment by swsnr** [comment]
Indeed, I can reproduce this.  I'll fix this.
