### ISSUE TITLE
Command line interface enhancements

### ISSUE THREAD

**Issue by StorageB** [swsnr/turnon#30]
Feature request to have additional Application Options in the command line interface:
- list devices (and associated MAC address, IP address, and status?)
- get status of individual device (maybe something like a command --device-status=LABEL)

**Comment by swsnr** [comment]
I can see why the first option might be useful, and I'll perhaps add it, but if the first one exists then what's the second one good for?

**Comment by swsnr** [comment]
I'll see if I can add the first option.
