### ISSUE TITLE
Can I wake up over DDNS and a specific port?

### ISSUE THREAD

**Issue by 7HE-W0R1D** [swsnr/turnon#39]
Thank you for creating this fantastic app!

I’m trying to remotely wake up my home PC using DDNS and port forwarding. For the external WOL port, I use a custom port (e.g., 3999). In other apps, I input myhostname.com as the hostname and 3999 as the WOL port, which works fine.

However, with this app, entering myhostname.com:3999 gives the error: Device not reachable: Error resolving "myhostname.com:3999": Name or service not known. Changing the external port to 9 sends the magic packet, but my PC doesn’t wake up.

Other WOL apps can wake my PC on both ports 9 and 3999. Could you please advise on what I might be doing wrong?

**Comment by swsnr** [comment]
Thanks but I'm afraid I can't help you.  I can't provide user support for a network and hardware configuration I do not know, and I do not know how these "other WOL apps" you're talking about work.

I'm surprised that this kind of remote wakeup works at all, in any kind of app: Normally unreachable systems drop out of ARP caches after some hours at which point wakeup packets to these addresses become unroutable.

If you wish to move this forward I need a _very detailed and precise_ description of your network setup, including all relevant forwarding rules, and a `wol` command line (see https://man.archlinux.org/man/extra/wol/wol.1.en) which successfully and reproducibly wakes up the target system.

Then I may be able to help but I can't make any promises. 

If you can make a pull request with necessary changes to this app to successfully wake up the system, that be even better.

Meanwhile I'll close this ticket as it is currently not actionable. 

Feel free to reopen if you can provide any of the aforementioned information.

**Comment by swsnr** [comment]
And I'd like to add that even if we figure out what's wrong any non-trivial changes to this app which are required to solve your issue would likely have to come from you.

I do not have this use case so I for my part don't want to spend too much time on this...

**Comment by swsnr** [comment]
Perhaps there's a misunderstanding: The host field is only used for pinging to see of the system is running, it's not used for wakeup.  This perhaps explains why you tried to put a port number in that field.  That won't work, wakeup packets always go to the unroutable broadcast address.

**Comment by 7HE-W0R1D** [comment]
Thanks for the clarification, I'll try find other app that suits my needs then

**Comment by swsnr** [comment]
Perhaps it does work in your setup, but you'd need to find out exactly how it works before I can make any necessary changes to this app. See above for what information I'd need.
