### ISSUE TITLE
Remember window dimensions (width and height)

### ISSUE THREAD

**Issue by nekohayo** [swsnr/turnon#62]
When you have more than a handful of devices, and/or devices with long/detailed names, it is a bit annoying to resize the window each time I start the application. That's extra work that the user should not have to do everytime.

Scrolling and wrapping is annoying, we should treat the window like a physical object that retains its properties, etc.

Some tips on how to do so: https://developer.gnome.org/documentation/tutorials/save-state.html

**Comment by swsnr** [comment]
@nekohayo 2.1.0 supports this now.  Does it work for you?
